### ISSUE TITLE
Sort schema versions by semantic versioning

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-entry-js#117]
# User story
As a user, I want to view the sorted schema versions, so I can find the appropriate one easier.

# Acceptance criteria
- [x] Given a user selects a schema, when they open the schema version dropdown menu, they will be sorted by semantic version with the latest at the top.
- [x] (Optional) Add unit test 

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

### Original Issue
**Is your feature request related to a problem? Please describe.**
When I click the "Select Schema Version" button, a list is displayed that is sorted lexicographical, so something like `0.1.0`, `0.1.1`, `0.1.19`, `0.1.2`.

**Describe the solution you'd like**
It'd be nicer if they sorted by semantic version.

**Describe alternatives you've considered**
Keeping the sort order as is.

**Additional context**

**Comment by helen-m-lin** [comment]
This feature was quite straightforward since I used a package to directly sort by semantic version. Setup and understanding the codebase was also straightforward due to familiarity with React and npm. The difficulty was creating a new test suite for the Dropdowns components since currently the repo does not have unit tests for UI components. This should make it easier in the future to add tests for React components.
