### ISSUE TITLE
add and update schemas

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-entry-js#20]
In preparation for various demos we'd like to run with scientists, let's add the rest of the schemas to the metadata entry app.

Acceptance criteria:

- [x] include [ephys_session](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/ephys/ephys_session.json)
- [x] include [ephys_rig](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/ephys/ephys_rig.json)
- [x] update [data_description](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/data_description.json)
- [x] update [subject](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/subject.json)
- [x] update [procedures](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/procedures.json)
- [x] include [imaging/instrument](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/imaging/instrument.json)

Nice to have: 
- [x] include [ophys_rig](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/ophys/ophys_rig.json)
- [x] include [ophys_session](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/ophys/ophys_session.json)
- [x] include [imaging/acquisition](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/imaging/acquisition.json)
- [x] include [processing](https://github.com/AllenNeuralDynamics/data_schema/blob/main/schemas/processing.json)

**Comment by mekhlakapoor** [comment]
- imaging instrument does not render because of [$ref issue](https://github.com/rjsf-team/react-jsonschema-form/issues/988)
- ophys rig devices rendering incorrectly (as a single entry rather than a section of devices)

**Comment by dyf** [comment]
@mekhlakapoor go ahead and rename `defs` to `definitions` in any schemas that you need to.

**Comment by mekhlakapoor** [comment]
Fixed the prior issue by fixing typos in the imaging instrument schema. 

Ophys rig devices is not rendering correctly due to the structure of the schema (as screenshotted) -- particularly because the devices is listed as a property field of type: string. I'm thinking we can change the schema to either remove "devices" and have all the device properties be individual fields, or change "devices" to an array, and instead have all the devices be items in the array. Let me know if there's a preference/another option and I can make it an issue in data_schema repo

<img width="1347" alt="Screen Shot 2022-10-07 at 4 41 31 PM" src="https://user-images.githubusercontent.com/54870020/194675818-eed9b56c-77fc-46de-abf6-fb10c721d6f5.png">

**Comment by dyf** [comment]
@mekhlakapoor `devices` should be an array

**Comment by saskiad** [comment]
Ophys rig is and ophys session are going to change a lot very soon, I'm currently working on them. So I'd leave them alone for now until I can put in my PR. Hopefully this weekend.

**Comment by saskiad** [comment]
Same for processing
